language: ruby
before_install: gem install bundler --pre
script: "DISPLAY=:99.0 bundle exec rspec spec"
notifications:
  email:
    - kennyadsl@gmail.com
    - mtylty@gmail.com
branches:
  only:
    - master
env:
  - CODECLIMATE_REPO_TOKEN=e2ce951cfe49257f658e6bd61d1cabe61648328c87a3f1a0908c4e4b3d9b2e7e
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
